<a href="https://colab.research.google.com/github/rabailkhan321/Data_Science_FA21-BSE-036/blob/main/Assignment4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [114]:
# Date: 11/12/23
# CSC461 – Assignment4 – NLP
# Full Name: Rabail Salman
# Registration Number: FA21-BSE-036
# A brief description: In this task, first I have found the bow,tf,idf and tfidf values of s1,s2 and s3.
# Then I computed the similarity between S1, S2, and S3 using cosine, manhattan, and euclidean distances.
import warnings
import numpy as np
warnings.filterwarnings("ignore")

In [115]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

import pandas as pd

In [116]:
s1 = "data science is one of the most important courses in computer science"
s2 = "this is one of the best data science courses"
s3 = "the data scientists perform data analysis"

In [117]:
data = [s1,s2,s3]
data

['data science is one of the most important courses in computer science',
 'this is one of the best data science courses',
 'the data scientists perform data analysis']

In [118]:
#Bag of words
count_vectorizer = CountVectorizer()
c_vector_matrix = count_vectorizer.fit_transform(data)
c_vector_matrix

<3x16 sparse matrix of type '<class 'numpy.int64'>'
	with 25 stored elements in Compressed Sparse Row format>

In [119]:
c_tokens = count_vectorizer.get_feature_names_out()
c_tokens

array(['analysis', 'best', 'computer', 'courses', 'data', 'important',
       'in', 'is', 'most', 'of', 'one', 'perform', 'science',
       'scientists', 'the', 'this'], dtype=object)

In [120]:
dataframebow = pd.DataFrame(data = c_vector_matrix.toarray(), columns = c_tokens)
dataframebow

analysis  best  computer  courses  data  important  in  is  most  of  one  \
0         0     0         1        1     1          1   1   1     1   1    1   
1         0     1         0        1     1          0   0   1     0   1    1   
2         1     0         0        0     2          0   0   0     0   0    0   

   perform  science  scientists  the  this  
0        0        2           0    1     0  
1        0        1           0    1     1  
2        1        0           1    1     0

In [121]:
#Term frequency
tf_matrix_exp1_normalized =c_vector_matrix.toarray() / c_vector_matrix .sum(axis=1).reshape(-1, 1)
df_tf_normalized = pd.DataFrame(tf_matrix_exp1_normalized, columns=c_tokens)
print(df_tf_normalized)

   analysis      best  computer   courses      data  important        in  \
0  0.000000  0.000000  0.083333  0.083333  0.083333   0.083333  0.083333   
1  0.000000  0.111111  0.000000  0.111111  0.111111   0.000000  0.000000   
2  0.166667  0.000000  0.000000  0.000000  0.333333   0.000000  0.000000   

         is      most        of       one   perform   science  scientists  \
0  0.083333  0.083333  0.083333  0.083333  0.000000  0.166667    0.000000   
1  0.111111  0.000000  0.111111  0.111111  0.000000  0.111111    0.000000   
2  0.000000  0.000000  0.000000  0.000000  0.166667  0.000000    0.166667   

        the      this  
0  0.083333  0.000000  
1  0.111111  0.111111  
2  0.166667  0.000000  


In [122]:
#idf
tf_vect = TfidfVectorizer(use_idf=True)
idf_matrix = tf_vect.fit_transform(data)
terms = tf_vect.get_feature_names_out()

idf_values = np.log(len(data) / ( 1+np.sum(idf_matrix > 0, axis=0)))

idf_values = np.array(idf_values).reshape(-1)
df_idf = pd.DataFrame(idf_values, index=terms, columns=["IDF"])
print(df_idf)

                 IDF
analysis    0.405465
best        0.405465
computer    0.405465
courses     0.000000
data       -0.287682
important   0.405465
in          0.405465
is          0.000000
most        0.405465
of          0.000000
one         0.000000
perform     0.405465
science     0.000000
scientists  0.405465
the        -0.287682
this        0.405465


In [123]:
#TF-IDF
tfidf_vect = TfidfVectorizer()
t_tfidf_matrix= tfidf_vect.fit_transform(data)
t_tfidf_matrix


<3x16 sparse matrix of type '<class 'numpy.float64'>'
	with 25 stored elements in Compressed Sparse Row format>

In [124]:
t_tokens = tfidf_vect.get_feature_names_out()
t_tokens

array(['analysis', 'best', 'computer', 'courses', 'data', 'important',
       'in', 'is', 'most', 'of', 'one', 'perform', 'science',
       'scientists', 'the', 'this'], dtype=object)

In [125]:
df_t_exp1 = pd.DataFrame(data = t_tfidf_matrix.toarray(), columns = t_tokens)
df_t_exp1

analysis      best  computer   courses      data  important        in  \
0  0.000000  0.000000  0.327476  0.249054  0.193412   0.327476  0.327476   
1  0.000000  0.422968  0.000000  0.321678  0.249812   0.000000  0.000000   
2  0.459115  0.000000  0.000000  0.000000  0.542321   0.000000  0.000000   

         is      most        of       one   perform   science  scientists  \
0  0.249054  0.327476  0.249054  0.249054  0.000000  0.498107    0.000000   
1  0.321678  0.000000  0.321678  0.321678  0.000000  0.321678    0.000000   
2  0.000000  0.000000  0.000000  0.000000  0.459115  0.000000    0.459115   

        the      this  
0  0.193412  0.000000  
1  0.249812  0.422968  
2  0.271161  0.000000

In [126]:
#cosine:
#bow
t_cosine_similarity_matrix_bow = cosine_similarity(c_vector_matrix)

df_cosine_bow = pd.DataFrame(t_cosine_similarity_matrix_bow, columns=["s1", "s2", "s3"], index=["s1", "s2", "s3"])
df_cosine_bow

s1        s2        s3
s1  1.000000  0.712697  0.283473
s2  0.712697  1.000000  0.353553
s3  0.283473  0.353553  1.000000

In [127]:
#cosine:
#tf
tf_matrix_exp1_normalized_array = np.asarray(tf_matrix_exp1_normalized)

t_cosine_similarity_matrix_tf = cosine_similarity(tf_matrix_exp1_normalized_array)

print(t_cosine_similarity_matrix_tf)


[[1.         0.71269665 0.28347335]
 [0.71269665 1.         0.35355339]
 [0.28347335 0.35355339 1.        ]]


In [128]:
#cosine:
#idf
idf_matrix_array = idf_matrix.toarray()  # Convert the sparse matrix to a NumPy array
t_cosine_similarity_matrix_idf = cosine_similarity(idf_matrix_array)
print(t_cosine_similarity_matrix_idf)

[[1.         0.57732419 0.15733751]
 [0.57732419 1.         0.20321737]
 [0.15733751 0.20321737 1.        ]]


In [129]:
#cosine:
#tfidf
t_cosine_similarity_matrix_tfidf = cosine_similarity(t_tfidf_matrix)
t_cosine_similarity_matrix_tfidf
df_t_similarity = pd.DataFrame(data = t_cosine_similarity_matrix_tfidf)
df_t_similarity

0         1         2
0  1.000000  0.577324  0.157338
1  0.577324  1.000000  0.203217
2  0.157338  0.203217  1.000000

In [130]:
#manhattan distance
from scipy.spatial.distance import cityblock

In [131]:
#manhattan distance bow
manhattan_distance_bow_s1ands2 = cityblock(dataframebow.iloc[0], dataframebow.iloc[1])
manhattan_distance_bow_s1ands3= cityblock(dataframebow.iloc[0], dataframebow.iloc[2])
manhattan_distance_bow_s2ands3 = cityblock(dataframebow.iloc[2], dataframebow.iloc[1])
print("manhattan_distance bow between s1 and s2 ")
print(manhattan_distance_bow_s1ands2)
print("manhattan_distance bow between s1 and s3 ")
print(manhattan_distance_bow_s1ands3)
print("manhattan_distance bow between s2 and s3")
print(manhattan_distance_bow_s2ands3)

manhattan_distance bow between s1 and s2 
7
manhattan_distance bow between s1 and s3 
14
manhattan_distance bow between s2 and s3
11


In [132]:
#manhattan distance tfidf
manhattan_distance_tfidf_s1ands2 = cityblock(df_t_exp1.iloc[0], df_t_exp1.iloc[1])
manhattan_distance_tfidf_s1ands3= cityblock(df_t_exp1.iloc[0], df_t_exp1.iloc[2])
manhattan_distance_tfidf_s2ands3 = cityblock(df_t_exp1.iloc[2], df_t_exp1.iloc[1])
print("manhattan_distance tfidf between s1 and s2 ")
print(manhattan_distance_tfidf_s1ands2)
print("manhattan_distance tfidf between s1 and s3 ")
print(manhattan_distance_tfidf_s1ands3)
print("manhattan_distance tfidf between s2 and s3")
print(manhattan_distance_tfidf_s2ands3)

manhattan_distance tfidf between s1 and s2 
2.735564680311888
manhattan_distance tfidf between s1 and s3 
4.608226815723473
manhattan_distance tfidf between s2 and s3
4.145530045552444


In [133]:
#manhattan distance tf
manhattan_distance_tf_s1ands2 = cityblock(df_tf_normalized.iloc[0], df_tf_normalized.iloc[1])
manhattan_distance_tf_s1ands3= cityblock(df_tf_normalized.iloc[0], df_tf_normalized.iloc[2])
manhattan_distance_tf_s2ands3 = cityblock(df_tf_normalized.iloc[2], df_tf_normalized.iloc[1])
print("manhattan_distance tf between s1 and s2 ")
print(manhattan_distance_tf_s1ands2)
print("manhattan_distance tf between s1 and s3 ")
print(manhattan_distance_tf_s1ands3)
print("manhattan_distance tf between s2 and s3")
print(manhattan_distance_tf_s2ands3)


manhattan_distance tf between s1 and s2 
0.7777777777777777
manhattan_distance tf between s1 and s3 
1.6666666666666665
manhattan_distance tf between s2 and s3
1.5555555555555554


In [134]:
#manhattan distance idf
manhattan_distance_idf_s1ands2 = cityblock(df_idf.iloc[0], df_idf.iloc[1])
manhattan_distance_idf_s1ands3= cityblock(df_idf.iloc[0], df_idf.iloc[2])
manhattan_distance_idf_s2ands3 = cityblock(df_idf.iloc[2], df_idf.iloc[1])
print("manhattan_distance idf between s1 and s2 ")
print(manhattan_distance_idf_s1ands2)
print("manhattan_distance idf between s1 and s3 ")
print(manhattan_distance_idf_s1ands3)
print("manhattan_distance idf between s2 and s3")
print(manhattan_distance_idf_s2ands3)



manhattan_distance idf between s1 and s2 
0.0
manhattan_distance idf between s1 and s3 
0.0
manhattan_distance idf between s2 and s3
0.0


In [135]:
#euclidean distance
import math

In [136]:
#euclidean distance bow
euclidean_distance_bow_s1ands2 = math.dist(dataframebow.iloc[0], dataframebow.iloc[1])
euclidean_distance_bow_s1ands3= math.dist(dataframebow.iloc[0], dataframebow.iloc[2])
euclidean_distance_bow_s2ands3 = math.dist(dataframebow.iloc[2], dataframebow.iloc[1])
print("euclidean_distance bow between s1 and s2 ")
print(euclidean_distance_bow_s1ands2)
print("euclidean_distance bow between s1 and s3 ")
print(euclidean_distance_bow_s1ands3)
print("euclidean_distance bow between s2 and s3")
print(euclidean_distance_bow_s2ands3)


euclidean_distance bow between s1 and s2 
2.6457513110645907
euclidean_distance bow between s1 and s3 
4.0
euclidean_distance bow between s2 and s3
3.3166247903554


In [137]:
#euclidean distance tfidf
euclidean_distance_tfidf_s1ands2 = math.dist(df_t_exp1.iloc[0], df_t_exp1.iloc[1])
euclidean_distance_tfidf_s1ands3= math.dist(df_t_exp1.iloc[0], df_t_exp1.iloc[2])
euclidean_distance_tfidf_s2ands3 = math.dist(df_t_exp1.iloc[2], df_t_exp1.iloc[1])
print("euclidean_distance tfidf between s1 and s2 ")
print(euclidean_distance_tfidf_s1ands2)
print("euclidean_distance tfidf between s1 and s3 ")
print(euclidean_distance_tfidf_s1ands3)
print("euclidean_distance tfidf between s2 and s3")
print(euclidean_distance_tfidf_s2ands3)

euclidean_distance tfidf between s1 and s2 
0.9194300544993212
euclidean_distance tfidf between s1 and s3 
1.2982006665010317
euclidean_distance tfidf between s2 and s3
1.2623649438617415


In [138]:
#euclidean distance tf
euclidean_distance_tf_s1ands2 = math.dist(df_tf_normalized.iloc[0], df_tf_normalized.iloc[1])
euclidean_distance_tf_s1ands3= math.dist(df_tf_normalized.iloc[0], df_tf_normalized.iloc[2])
euclidean_distance_tf_s2ands3 = math.dist(df_tf_normalized.iloc[2], df_tf_normalized.iloc[1])
print("euclidean_distance tf between s1 and s2 ")
print(euclidean_distance_tf_s1ands2)
print("euclidean_distance tf between s1 and s3 ")
print(euclidean_distance_tf_s1ands3)
print("euclidean_distance tf between s2 and s3")
print(euclidean_distance_tf_s2ands3)

euclidean_distance tf between s1 and s2 
0.24532669073132907
euclidean_distance tf between s1 and s3 
0.485912657903775
euclidean_distance tf between s2 and s3
0.4714045207910317


In [139]:
#euclidean distance idf
euclidean_distance_idf_s1ands2 = math.dist(df_idf.iloc[0], df_idf.iloc[1])
euclidean_distance_idf_s1ands3= math.dist(df_idf.iloc[0], df_idf.iloc[2])
euclidean_distance_idf_s2ands3 = math.dist(df_idf.iloc[2], df_idf.iloc[1])
print("euclidean_distance idf between s1 and s2 ")
print(euclidean_distance_idf_s1ands2)
print("euclidean_distance idf between s1 and s3 ")
print(euclidean_distance_idf_s1ands3)
print("euclidean_distance idf between s2 and s3")
print(euclidean_distance_idf_s2ands3)

euclidean_distance idf between s1 and s2 
0.0
euclidean_distance idf between s1 and s3 
0.0
euclidean_distance idf between s2 and s3
0.0
